# Generated by Django 5.0.3 on 2024-03-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='pre_image',
            field=models.ImageField(null=True, upload_to='static/img/upload'),
        ),
    ]
