# Generated by Django 5.0.3 on 2024-03-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_court_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='pre_image',
            field=models.ImageField(upload_to='static/img/upload'),
        ),
    ]
