# Generated by Django 5.0.3 on 2024-03-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='period',
            new_name='name',
        ),
    ]
