# Generated by Django 5.0.3 on 2024-03-29 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_period_sessions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('single', '1 Person'), ('child', 'Child Under 18'), ('double', 'Double (4 persons)'), ('couple', 'Couple'), ('family', 'Family')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^07\\d{8}$', 'Phone number must start with 07 and have 8 digits')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.court')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sessions')),
            ],
        ),
    ]
