# Generated by Django 5.0.3 on 2024-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_booking_options_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pendig', 'Pendig'), ('done', 'Done'), ('paid', 'Paid')], default='pendig', max_length=10),
        ),
    ]
