# Generated by Django 5.0.3 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_booking_options_sessions_istainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='pre_image',
            field=models.ImageField(upload_to='img/upload'),
        ),
    ]
